#!/bin/sh
# symlink to .git/hooks/ in repository
while read local_ref local_sha remote_ref remote_sha
do
  if [ "$remote_ref" = "refs/heads/source" ]
  then
    echo 'pushing public folder to master...'
    hugo 
    echo marcbecc.me > public/CNAME
    ghp-import -m "Generate Pelican site" -b master public
    git push --no-verify origin master
    hugo
  fi
done

exit 0
